# Generate embedded_shaders.cpp from shader files in SHADERS_DIR
file(GLOB SHADER_FILES "${SHADERS_DIR}/*.vert" "${SHADERS_DIR}/*.frag")
list(SORT SHADER_FILES)

set(CONTENT "/* Copyright (c) 2025 Otto Link. Distributed under the terms of the GNU General Public\n   License. The full license is in the file LICENSE, distributed with this software. */\n")
string(APPEND CONTENT "/* Auto-generated by CMake. Do not edit. */\n")
string(APPEND CONTENT "#include \"qtr/shader.hpp\"\n\n")
string(APPEND CONTENT "namespace qtr\n{\n\n")

foreach(SHADER_FILE ${SHADER_FILES})
  get_filename_component(FNAME ${SHADER_FILE} NAME)
  string(REPLACE ".vert" "_vertex" VAR_NAME "${FNAME}")
  string(REPLACE ".frag" "_frag" VAR_NAME "${VAR_NAME}")

  file(READ "${SHADER_FILE}" HEX_STR HEX)
  string(REGEX MATCHALL ".." HEX_LIST "${HEX_STR}")

  set(HEX_ARRAY "")
  set(COUNT 0)
  foreach(HEX_BYTE ${HEX_LIST})
    string(APPEND HEX_ARRAY "0x${HEX_BYTE}, ")
    math(EXPR COUNT "${COUNT} + 1")
    math(EXPR WRAP "${COUNT} % 20")
    if(WRAP EQUAL 0)
      string(APPEND HEX_ARRAY "\n  ")
    endif()
  endforeach()

  string(APPEND CONTENT "// --- ${FNAME}\n\n")
  string(APPEND CONTENT "static const unsigned char ${VAR_NAME}_data[] = {\n  ${HEX_ARRAY}0x00\n};\n\n")
  string(APPEND CONTENT "const std::string ${VAR_NAME}(reinterpret_cast<const char*>(${VAR_NAME}_data), sizeof(${VAR_NAME}_data) - 1);\n\n")
endforeach()

string(APPEND CONTENT "} // namespace qtr\n")

file(WRITE "${OUTPUT_FILE}" "${CONTENT}")
